# Generated by Django 3.0.8 on 2020-09-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='descriptions',
            new_name='description',
        ),
    ]
