# Generated by Django 3.1.1 on 2020-10-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funccrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='FuncBlog',
        ),
    ]
